### ISSUE TITLE
potential merge conflict

### ISSUE THREAD

**Issue by walterjamesperry** [abigailroberg/bait-and-tracker#14]
I noticed in kimberly/styles branch inside config/connection.js the port is changed to 3002. This needs to be changed to 3306. Unless Kims MySQL Server is set to that port. The team should discuss this. My advice is to set all your computers up to use the same ports to avoid merge conflict. Any action that can eliminate potential issues should be carried out. The instructional team wants to build up your good development practices during this project. So in the planning stage, everyone should have compared notes on changes they have made to their machines.

Also, another issue is Github issues is not being used as it should be unless you are using another project management tool.

**Comment by coderjake91** [comment]
We noticed this issue when we were testing the routes last Wednesday. We have changed the PORT to 3306, and will make sure everyone is on the same page this Monday during class. I think you mention in another issue that we should be using GitHub or some other project management tool to better track these things, we will discuss this on Monday too- I think that is good advice

**Comment by kimcc** [comment]
Closing as resolved
