### ISSUE TITLE
issue in Jacob/controller branch

### ISSUE THREAD

**Issue by walterjamesperry** [abigailroberg/bait-and-tracker#16]
The server.js file is requiring the package "express-handlebars". Jacob needs to npm install this package.

**Comment by coderjake91** [comment]
yes, I added that require statement in anticipation of an eventual merge with the 'views' code, at that time I had not rendered any server-side data into templates, at this point I just installed it and it is tracked in my package.json now, you should see it in my next commit

**Comment by coderjake91** [comment]
"express-handlebars" npm package is now installed on my branch
