### ISSUE TITLE
Image database Implementation

### ISSUE THREAD

**Issue by Falciform-mv** [abigailroberg/bait-and-tracker#4]
Use Base64 to store and allow posting of images to database

**Comment by coderjake91** [comment]
we ended up going with the AWS S3 bucket solution where images are uploaded as Files, then a PUT request is performed, the image is stored externally on the AWS S3 bait-and-tracker bucket, then the urls are stored in the picture attribute on the fish model, the backend requests then serve up the url string to the handlebars template
